depends:
    - can-bootloader
    - kprintf
    - crc

target.arm:
    - src/main.c
    - src/vector_table.c
    - src/can_interface.c
    - src/debug.c
    - src/reduce_binary.c

dependency-dir: ./dependencies

templates:
    include.jinja: include.mk
